### ISSUE TITLE
InstallAWT.exe silently/unattended

### ISSUE THREAD

**Issue by arpalmares** [msintuneappsdk/intune-app-wrapping-tool-android#45]
We are using Azure DevOps to create a CI/CD pipeline for our mobile build.
We were able to successfully integrate the latest wrapping tool in the iOS pipeline but struggling to get the latest tool to be used in android.

This is just to ensure that our builds are always using the latest wrapping tool.
In installing the wrapper for android, we are unable to install the exe file silently or unattended mode because of the dialog boxes that needs to be accepted.

Is this possible to run in a PowerShell script? I tried variations and could not find any help for the parameters that the exe file accepts.

InstallAWT.exe /silent
InstallAWT.exe /unattended
InstallAWT.exe /?
InstallAWT.exe /help

**Comment by Nathan187** [comment]
did you ever get an answer to this?

**Comment by glucaci** [comment]
@aanavath @meghandaly @msintuneappsdk there is any plan to support command line setup?

**Comment by Heimo001** [comment]
Install it on your computer, zip "\Program Files (x86)\Microsoft Intune Mobile Application Management\" and upload the zip to any artifact storage.

Download and extract the zip to your agents "Program Files (x86)" directory.

**Comment by iamrakesh** [comment]
We too did it same way as explained by @Heimo001

**Comment by d2callpod** [comment]
@Heimo001 solution works for me as well. But it's not ideal. 

The wrapper should support this. It's something that is highly likely to be used with CI.

**Comment by a-pagano** [comment]
@Heimo001 solution works for us as well. In case this could be helpful to another poor soul that ends up on this issue: you can find the extracted tool (1.0.4549.6) in a zip archive in this gist https://gist.github.com/a-pagano/2ee45c9afc2dddbacb4cae0daa61804c

Create a release with tag `Intune` and upload the zip as an artifact. Then you can use the tool in your Action workflow like so:

```yaml
name: Intune App Wrapping
on:
  workflow_call:
    inputs:
        artifact_name:
            required: true
            type: string
            description: 'Name of the artifact containing the APK to wrap'
  
jobs:
  wrap-apk:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: apk-artifacts
      - name: Download and extract Intune MAM tool
        run: |
          gh release download Intune --pattern "Microsoft.Intune.Mobile.Application.Management.zip"
          powershell -Command "Expand-Archive -Path Microsoft.Intune.Mobile.Application.Management.zip -DestinationPath '.' -Force"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Wrap APK
        run: |
          $apkFile = Get-ChildItem -Path "apk-artifacts" -Filter "*.apk" -Recurse | Select-Object -First 1
          if ($apkFile) {
            Write-Host "Found APK: $($apkFile.FullName)"

            # Import the PowerShell module
            $modulePath = Resolve-Path "Microsoft Intune Mobile Application Management\Android\App Wrapping Tool\IntuneAppWrappingTool.psm1"
            Write-Host "Module path: $modulePath"
            Write-Host "Module exists: $(Test-Path $modulePath)"

            Import-Module $modulePath.Path

            $outputName = Join-Path (Get-Location) "$($apkFile.BaseName)-wrapped.apk"
            Write-Host "Output path: $outputName"

            Invoke-AppWrappingTool -InputPath $apkFile.FullName -OutputPath $outputName -Verbose

            Write-Host "Checking for output file: $(Test-Path $outputName)"
            Get-ChildItem -Path "." -Filter "*wrapped*" | Format-Table
          } else {
            Write-Error "No APK file found in artifacts"
            exit 1
          }
```
